set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Joseph Diza") # required
set(CPACK_PACKAGE_DIRECTORY "packages/${CMAKE_PROJECT_NAME}-${CMAKE_PROJECT_VERSION}")
#set(CPACK_DEBIAN_PACKAGE_DEPENDS "restclient-cpp")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_GENERATOR "DEB;TGZ;ZIP") # Create .deb, .tgz, .zip files
include(CPack)
